// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Traj.proto

package com.lsy.myhadoop.spark2.kryo;

public final class TrajPb {
  private TrajPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrderTrajOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string order_id = 1;
    /**
     * <code>optional string order_id = 1;</code>
     */
    boolean hasOrderId();
    /**
     * <code>optional string order_id = 1;</code>
     */
    String getOrderId();
    /**
     * <code>optional string order_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    // repeated .map_match_point_pb point_list = 2;
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    java.util.List<map_match_point_pb>
        getPointListList();
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    TrajPb.map_match_point_pb getPointList(int index);
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    int getPointListCount();
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    java.util.List<? extends map_match_point_pbOrBuilder>
        getPointListOrBuilderList();
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    TrajPb.map_match_point_pbOrBuilder getPointListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code OrderTraj}
   */
  public static final class OrderTraj extends
      com.google.protobuf.GeneratedMessage
      implements OrderTrajOrBuilder {
    // Use OrderTraj.newBuilder() to construct.
    private OrderTraj(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OrderTraj(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OrderTraj defaultInstance;
    public static OrderTraj getDefaultInstance() {
      return defaultInstance;
    }

    public OrderTraj getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OrderTraj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              orderId_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                pointList_ = new java.util.ArrayList<map_match_point_pb>();
                mutable_bitField0_ |= 0x00000002;
              }
              pointList_.add(input.readMessage(TrajPb.map_match_point_pb.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          pointList_ = java.util.Collections.unmodifiableList(pointList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TrajPb.internal_static_OrderTraj_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TrajPb.internal_static_OrderTraj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TrajPb.OrderTraj.class, TrajPb.OrderTraj.Builder.class);
    }

    public static com.google.protobuf.Parser<OrderTraj> PARSER =
        new com.google.protobuf.AbstractParser<OrderTraj>() {
      public OrderTraj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderTraj(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<OrderTraj> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string order_id = 1;
    public static final int ORDER_ID_FIELD_NUMBER = 1;
    private Object orderId_;
    /**
     * <code>optional string order_id = 1;</code>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string order_id = 1;</code>
     */
    public String getOrderId() {
      Object ref = orderId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string order_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .map_match_point_pb point_list = 2;
    public static final int POINT_LIST_FIELD_NUMBER = 2;
    private java.util.List<map_match_point_pb> pointList_;
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    public java.util.List<map_match_point_pb> getPointListList() {
      return pointList_;
    }
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    public java.util.List<? extends map_match_point_pbOrBuilder>
        getPointListOrBuilderList() {
      return pointList_;
    }
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    public int getPointListCount() {
      return pointList_.size();
    }
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    public TrajPb.map_match_point_pb getPointList(int index) {
      return pointList_.get(index);
    }
    /**
     * <code>repeated .map_match_point_pb point_list = 2;</code>
     */
    public TrajPb.map_match_point_pbOrBuilder getPointListOrBuilder(
        int index) {
      return pointList_.get(index);
    }

    private void initFields() {
      orderId_ = "";
      pointList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPointListCount(); i++) {
        if (!getPointList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOrderIdBytes());
      }
      for (int i = 0; i < pointList_.size(); i++) {
        output.writeMessage(2, pointList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOrderIdBytes());
      }
      for (int i = 0; i < pointList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pointList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TrajPb.OrderTraj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TrajPb.OrderTraj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TrajPb.OrderTraj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TrajPb.OrderTraj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TrajPb.OrderTraj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TrajPb.OrderTraj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TrajPb.OrderTraj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TrajPb.OrderTraj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TrajPb.OrderTraj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TrajPb.OrderTraj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TrajPb.OrderTraj prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderTraj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TrajPb.OrderTrajOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TrajPb.internal_static_OrderTraj_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TrajPb.internal_static_OrderTraj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TrajPb.OrderTraj.class, TrajPb.OrderTraj.Builder.class);
      }

      // Construct using com.didichuxing.sts.traj.core.model.TrajPb.OrderTraj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPointListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        orderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pointListBuilder_ == null) {
          pointList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          pointListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TrajPb.internal_static_OrderTraj_descriptor;
      }

      public TrajPb.OrderTraj getDefaultInstanceForType() {
        return TrajPb.OrderTraj.getDefaultInstance();
      }

      public TrajPb.OrderTraj build() {
        TrajPb.OrderTraj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TrajPb.OrderTraj buildPartial() {
        TrajPb.OrderTraj result = new TrajPb.OrderTraj(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderId_ = orderId_;
        if (pointListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            pointList_ = java.util.Collections.unmodifiableList(pointList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.pointList_ = pointList_;
        } else {
          result.pointList_ = pointListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TrajPb.OrderTraj) {
          return mergeFrom((TrajPb.OrderTraj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TrajPb.OrderTraj other) {
        if (other == TrajPb.OrderTraj.getDefaultInstance()) return this;
        if (other.hasOrderId()) {
          bitField0_ |= 0x00000001;
          orderId_ = other.orderId_;
          onChanged();
        }
        if (pointListBuilder_ == null) {
          if (!other.pointList_.isEmpty()) {
            if (pointList_.isEmpty()) {
              pointList_ = other.pointList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePointListIsMutable();
              pointList_.addAll(other.pointList_);
            }
            onChanged();
          }
        } else {
          if (!other.pointList_.isEmpty()) {
            if (pointListBuilder_.isEmpty()) {
              pointListBuilder_.dispose();
              pointListBuilder_ = null;
              pointList_ = other.pointList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              pointListBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPointListFieldBuilder() : null;
            } else {
              pointListBuilder_.addAllMessages(other.pointList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPointListCount(); i++) {
          if (!getPointList(i).isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TrajPb.OrderTraj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TrajPb.OrderTraj) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string order_id = 1;
      private Object orderId_ = "";
      /**
       * <code>optional string order_id = 1;</code>
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string order_id = 1;</code>
       */
      public String getOrderId() {
        Object ref = orderId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string order_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string order_id = 1;</code>
       */
      public Builder setOrderId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string order_id = 1;</code>
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string order_id = 1;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }

      // repeated .map_match_point_pb point_list = 2;
      private java.util.List<map_match_point_pb> pointList_ =
        java.util.Collections.emptyList();
      private void ensurePointListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pointList_ = new java.util.ArrayList<map_match_point_pb>(pointList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          map_match_point_pb, map_match_point_pb.Builder, map_match_point_pbOrBuilder> pointListBuilder_;

      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public java.util.List<map_match_point_pb> getPointListList() {
        if (pointListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pointList_);
        } else {
          return pointListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public int getPointListCount() {
        if (pointListBuilder_ == null) {
          return pointList_.size();
        } else {
          return pointListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public TrajPb.map_match_point_pb getPointList(int index) {
        if (pointListBuilder_ == null) {
          return pointList_.get(index);
        } else {
          return pointListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public Builder setPointList(
          int index, TrajPb.map_match_point_pb value) {
        if (pointListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointListIsMutable();
          pointList_.set(index, value);
          onChanged();
        } else {
          pointListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public Builder setPointList(
          int index, TrajPb.map_match_point_pb.Builder builderForValue) {
        if (pointListBuilder_ == null) {
          ensurePointListIsMutable();
          pointList_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public Builder addPointList(TrajPb.map_match_point_pb value) {
        if (pointListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointListIsMutable();
          pointList_.add(value);
          onChanged();
        } else {
          pointListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public Builder addPointList(
          int index, TrajPb.map_match_point_pb value) {
        if (pointListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointListIsMutable();
          pointList_.add(index, value);
          onChanged();
        } else {
          pointListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public Builder addPointList(
          TrajPb.map_match_point_pb.Builder builderForValue) {
        if (pointListBuilder_ == null) {
          ensurePointListIsMutable();
          pointList_.add(builderForValue.build());
          onChanged();
        } else {
          pointListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public Builder addPointList(
          int index, TrajPb.map_match_point_pb.Builder builderForValue) {
        if (pointListBuilder_ == null) {
          ensurePointListIsMutable();
          pointList_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public Builder addAllPointList(
          Iterable<? extends map_match_point_pb> values) {
        if (pointListBuilder_ == null) {
          ensurePointListIsMutable();
          super.addAll(values, pointList_);
          onChanged();
        } else {
          pointListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public Builder clearPointList() {
        if (pointListBuilder_ == null) {
          pointList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          pointListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public Builder removePointList(int index) {
        if (pointListBuilder_ == null) {
          ensurePointListIsMutable();
          pointList_.remove(index);
          onChanged();
        } else {
          pointListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public TrajPb.map_match_point_pb.Builder getPointListBuilder(
          int index) {
        return getPointListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public TrajPb.map_match_point_pbOrBuilder getPointListOrBuilder(
          int index) {
        if (pointListBuilder_ == null) {
          return pointList_.get(index);  } else {
          return pointListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public java.util.List<? extends map_match_point_pbOrBuilder>
           getPointListOrBuilderList() {
        if (pointListBuilder_ != null) {
          return pointListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pointList_);
        }
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public TrajPb.map_match_point_pb.Builder addPointListBuilder() {
        return getPointListFieldBuilder().addBuilder(
            TrajPb.map_match_point_pb.getDefaultInstance());
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public TrajPb.map_match_point_pb.Builder addPointListBuilder(
          int index) {
        return getPointListFieldBuilder().addBuilder(
            index, TrajPb.map_match_point_pb.getDefaultInstance());
      }
      /**
       * <code>repeated .map_match_point_pb point_list = 2;</code>
       */
      public java.util.List<map_match_point_pb.Builder>
           getPointListBuilderList() {
        return getPointListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          map_match_point_pb, map_match_point_pb.Builder, map_match_point_pbOrBuilder>
          getPointListFieldBuilder() {
        if (pointListBuilder_ == null) {
          pointListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              map_match_point_pb, map_match_point_pb.Builder, map_match_point_pbOrBuilder>(
                  pointList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          pointList_ = null;
        }
        return pointListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:OrderTraj)
    }

    static {
      defaultInstance = new OrderTraj(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OrderTraj)
  }

  public interface map_match_point_pbOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string user_id = 1;
    /**
     * <code>required string user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string user_id = 1;</code>
     */
    String getUserId();
    /**
     * <code>required string user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    // required int32 proj_x = 2;
    /**
     * <code>required int32 proj_x = 2;</code>
     */
    boolean hasProjX();
    /**
     * <code>required int32 proj_x = 2;</code>
     */
    int getProjX();

    // required int32 proj_y = 3;
    /**
     * <code>required int32 proj_y = 3;</code>
     */
    boolean hasProjY();
    /**
     * <code>required int32 proj_y = 3;</code>
     */
    int getProjY();

    // repeated int64 link_id_vec = 4;
    /**
     * <code>repeated int64 link_id_vec = 4;</code>
     */
    java.util.List<Long> getLinkIdVecList();
    /**
     * <code>repeated int64 link_id_vec = 4;</code>
     */
    int getLinkIdVecCount();
    /**
     * <code>repeated int64 link_id_vec = 4;</code>
     */
    long getLinkIdVec(int index);

    // required int32 link_pass_dist = 5;
    /**
     * <code>required int32 link_pass_dist = 5;</code>
     */
    boolean hasLinkPassDist();
    /**
     * <code>required int32 link_pass_dist = 5;</code>
     */
    int getLinkPassDist();

    // required int32 timestamp = 6;
    /**
     * <code>required int32 timestamp = 6;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int32 timestamp = 6;</code>
     */
    int getTimestamp();

    // optional int32 src_x = 7;
    /**
     * <code>optional int32 src_x = 7;</code>
     */
    boolean hasSrcX();
    /**
     * <code>optional int32 src_x = 7;</code>
     */
    int getSrcX();

    // optional int32 src_y = 8;
    /**
     * <code>optional int32 src_y = 8;</code>
     */
    boolean hasSrcY();
    /**
     * <code>optional int32 src_y = 8;</code>
     */
    int getSrcY();

    // optional float point_speed = 9;
    /**
     * <code>optional float point_speed = 9;</code>
     */
    boolean hasPointSpeed();
    /**
     * <code>optional float point_speed = 9;</code>
     */
    float getPointSpeed();

    // optional float point_direction = 10;
    /**
     * <code>optional float point_direction = 10;</code>
     */
    boolean hasPointDirection();
    /**
     * <code>optional float point_direction = 10;</code>
     */
    float getPointDirection();

    // optional float line_speed = 11;
    /**
     * <code>optional float line_speed = 11;</code>
     */
    boolean hasLineSpeed();
    /**
     * <code>optional float line_speed = 11;</code>
     */
    float getLineSpeed();

    // optional float line_direction = 12;
    /**
     * <code>optional float line_direction = 12;</code>
     */
    boolean hasLineDirection();
    /**
     * <code>optional float line_direction = 12;</code>
     */
    float getLineDirection();

    // optional int32 certainty = 13;
    /**
     * <code>optional int32 certainty = 13;</code>
     */
    boolean hasCertainty();
    /**
     * <code>optional int32 certainty = 13;</code>
     */
    int getCertainty();

    // optional int32 biztype = 14;
    /**
     * <code>optional int32 biztype = 14;</code>
     */
    boolean hasBiztype();
    /**
     * <code>optional int32 biztype = 14;</code>
     */
    int getBiztype();

    // optional bytes role = 15;
    /**
     * <code>optional bytes role = 15;</code>
     */
    boolean hasRole();
    /**
     * <code>optional bytes role = 15;</code>
     */
    com.google.protobuf.ByteString getRole();

    // optional int32 map_version = 16;
    /**
     * <code>optional int32 map_version = 16;</code>
     */
    boolean hasMapVersion();
    /**
     * <code>optional int32 map_version = 16;</code>
     */
    int getMapVersion();

    // optional int32 bizstatus = 17;
    /**
     * <code>optional int32 bizstatus = 17;</code>
     */
    boolean hasBizstatus();
    /**
     * <code>optional int32 bizstatus = 17;</code>
     */
    int getBizstatus();

    // optional int64 phone = 18;
    /**
     * <code>optional int64 phone = 18;</code>
     */
    boolean hasPhone();
    /**
     * <code>optional int64 phone = 18;</code>
     */
    long getPhone();
  }
  /**
   * Protobuf type {@code map_match_point_pb}
   */
  public static final class map_match_point_pb extends
      com.google.protobuf.GeneratedMessage
      implements map_match_point_pbOrBuilder {
    // Use map_match_point_pb.newBuilder() to construct.
    private map_match_point_pb(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private map_match_point_pb(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final map_match_point_pb defaultInstance;
    public static map_match_point_pb getDefaultInstance() {
      return defaultInstance;
    }

    public map_match_point_pb getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private map_match_point_pb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              projX_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              projY_ = input.readInt32();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                linkIdVec_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              linkIdVec_.add(input.readInt64());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                linkIdVec_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                linkIdVec_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              linkPassDist_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              srcX_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              srcY_ = input.readInt32();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000080;
              pointSpeed_ = input.readFloat();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000100;
              pointDirection_ = input.readFloat();
              break;
            }
            case 93: {
              bitField0_ |= 0x00000200;
              lineSpeed_ = input.readFloat();
              break;
            }
            case 101: {
              bitField0_ |= 0x00000400;
              lineDirection_ = input.readFloat();
              break;
            }
            case 104: {
              bitField0_ |= 0x00000800;
              certainty_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00001000;
              biztype_ = input.readInt32();
              break;
            }
            case 122: {
              bitField0_ |= 0x00002000;
              role_ = input.readBytes();
              break;
            }
            case 128: {
              bitField0_ |= 0x00004000;
              mapVersion_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00008000;
              bizstatus_ = input.readInt32();
              break;
            }
            case 144: {
              bitField0_ |= 0x00010000;
              phone_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          linkIdVec_ = java.util.Collections.unmodifiableList(linkIdVec_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TrajPb.internal_static_map_match_point_pb_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TrajPb.internal_static_map_match_point_pb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TrajPb.map_match_point_pb.class, TrajPb.map_match_point_pb.Builder.class);
    }

    public static com.google.protobuf.Parser<map_match_point_pb> PARSER =
        new com.google.protobuf.AbstractParser<map_match_point_pb>() {
      public map_match_point_pb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new map_match_point_pb(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<map_match_point_pb> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private Object userId_;
    /**
     * <code>required string user_id = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user_id = 1;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 proj_x = 2;
    public static final int PROJ_X_FIELD_NUMBER = 2;
    private int projX_;
    /**
     * <code>required int32 proj_x = 2;</code>
     */
    public boolean hasProjX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 proj_x = 2;</code>
     */
    public int getProjX() {
      return projX_;
    }

    // required int32 proj_y = 3;
    public static final int PROJ_Y_FIELD_NUMBER = 3;
    private int projY_;
    /**
     * <code>required int32 proj_y = 3;</code>
     */
    public boolean hasProjY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 proj_y = 3;</code>
     */
    public int getProjY() {
      return projY_;
    }

    // repeated int64 link_id_vec = 4;
    public static final int LINK_ID_VEC_FIELD_NUMBER = 4;
    private java.util.List<Long> linkIdVec_;
    /**
     * <code>repeated int64 link_id_vec = 4;</code>
     */
    public java.util.List<Long>
        getLinkIdVecList() {
      return linkIdVec_;
    }
    /**
     * <code>repeated int64 link_id_vec = 4;</code>
     */
    public int getLinkIdVecCount() {
      return linkIdVec_.size();
    }
    /**
     * <code>repeated int64 link_id_vec = 4;</code>
     */
    public long getLinkIdVec(int index) {
      return linkIdVec_.get(index);
    }

    // required int32 link_pass_dist = 5;
    public static final int LINK_PASS_DIST_FIELD_NUMBER = 5;
    private int linkPassDist_;
    /**
     * <code>required int32 link_pass_dist = 5;</code>
     */
    public boolean hasLinkPassDist() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 link_pass_dist = 5;</code>
     */
    public int getLinkPassDist() {
      return linkPassDist_;
    }

    // required int32 timestamp = 6;
    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private int timestamp_;
    /**
     * <code>required int32 timestamp = 6;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 timestamp = 6;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    // optional int32 src_x = 7;
    public static final int SRC_X_FIELD_NUMBER = 7;
    private int srcX_;
    /**
     * <code>optional int32 src_x = 7;</code>
     */
    public boolean hasSrcX() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 src_x = 7;</code>
     */
    public int getSrcX() {
      return srcX_;
    }

    // optional int32 src_y = 8;
    public static final int SRC_Y_FIELD_NUMBER = 8;
    private int srcY_;
    /**
     * <code>optional int32 src_y = 8;</code>
     */
    public boolean hasSrcY() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 src_y = 8;</code>
     */
    public int getSrcY() {
      return srcY_;
    }

    // optional float point_speed = 9;
    public static final int POINT_SPEED_FIELD_NUMBER = 9;
    private float pointSpeed_;
    /**
     * <code>optional float point_speed = 9;</code>
     */
    public boolean hasPointSpeed() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional float point_speed = 9;</code>
     */
    public float getPointSpeed() {
      return pointSpeed_;
    }

    // optional float point_direction = 10;
    public static final int POINT_DIRECTION_FIELD_NUMBER = 10;
    private float pointDirection_;
    /**
     * <code>optional float point_direction = 10;</code>
     */
    public boolean hasPointDirection() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional float point_direction = 10;</code>
     */
    public float getPointDirection() {
      return pointDirection_;
    }

    // optional float line_speed = 11;
    public static final int LINE_SPEED_FIELD_NUMBER = 11;
    private float lineSpeed_;
    /**
     * <code>optional float line_speed = 11;</code>
     */
    public boolean hasLineSpeed() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional float line_speed = 11;</code>
     */
    public float getLineSpeed() {
      return lineSpeed_;
    }

    // optional float line_direction = 12;
    public static final int LINE_DIRECTION_FIELD_NUMBER = 12;
    private float lineDirection_;
    /**
     * <code>optional float line_direction = 12;</code>
     */
    public boolean hasLineDirection() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional float line_direction = 12;</code>
     */
    public float getLineDirection() {
      return lineDirection_;
    }

    // optional int32 certainty = 13;
    public static final int CERTAINTY_FIELD_NUMBER = 13;
    private int certainty_;
    /**
     * <code>optional int32 certainty = 13;</code>
     */
    public boolean hasCertainty() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 certainty = 13;</code>
     */
    public int getCertainty() {
      return certainty_;
    }

    // optional int32 biztype = 14;
    public static final int BIZTYPE_FIELD_NUMBER = 14;
    private int biztype_;
    /**
     * <code>optional int32 biztype = 14;</code>
     */
    public boolean hasBiztype() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 biztype = 14;</code>
     */
    public int getBiztype() {
      return biztype_;
    }

    // optional bytes role = 15;
    public static final int ROLE_FIELD_NUMBER = 15;
    private com.google.protobuf.ByteString role_;
    /**
     * <code>optional bytes role = 15;</code>
     */
    public boolean hasRole() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional bytes role = 15;</code>
     */
    public com.google.protobuf.ByteString getRole() {
      return role_;
    }

    // optional int32 map_version = 16;
    public static final int MAP_VERSION_FIELD_NUMBER = 16;
    private int mapVersion_;
    /**
     * <code>optional int32 map_version = 16;</code>
     */
    public boolean hasMapVersion() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 map_version = 16;</code>
     */
    public int getMapVersion() {
      return mapVersion_;
    }

    // optional int32 bizstatus = 17;
    public static final int BIZSTATUS_FIELD_NUMBER = 17;
    private int bizstatus_;
    /**
     * <code>optional int32 bizstatus = 17;</code>
     */
    public boolean hasBizstatus() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional int32 bizstatus = 17;</code>
     */
    public int getBizstatus() {
      return bizstatus_;
    }

    // optional int64 phone = 18;
    public static final int PHONE_FIELD_NUMBER = 18;
    private long phone_;
    /**
     * <code>optional int64 phone = 18;</code>
     */
    public boolean hasPhone() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional int64 phone = 18;</code>
     */
    public long getPhone() {
      return phone_;
    }

    private void initFields() {
      userId_ = "";
      projX_ = 0;
      projY_ = 0;
      linkIdVec_ = java.util.Collections.emptyList();
      linkPassDist_ = 0;
      timestamp_ = 0;
      srcX_ = 0;
      srcY_ = 0;
      pointSpeed_ = 0F;
      pointDirection_ = 0F;
      lineSpeed_ = 0F;
      lineDirection_ = 0F;
      certainty_ = 0;
      biztype_ = 0;
      role_ = com.google.protobuf.ByteString.EMPTY;
      mapVersion_ = 0;
      bizstatus_ = 0;
      phone_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProjX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProjY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLinkPassDist()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, projX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, projY_);
      }
      for (int i = 0; i < linkIdVec_.size(); i++) {
        output.writeInt64(4, linkIdVec_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, linkPassDist_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, srcX_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(8, srcY_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(9, pointSpeed_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFloat(10, pointDirection_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFloat(11, lineSpeed_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeFloat(12, lineDirection_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(13, certainty_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(14, biztype_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(15, role_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(16, mapVersion_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(17, bizstatus_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt64(18, phone_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, projX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, projY_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < linkIdVec_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(linkIdVec_.get(i));
        }
        size += dataSize;
        size += 1 * getLinkIdVecList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, linkPassDist_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, srcX_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, srcY_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, pointSpeed_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, pointDirection_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, lineSpeed_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, lineDirection_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, certainty_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, biztype_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, role_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, mapVersion_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, bizstatus_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(18, phone_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TrajPb.map_match_point_pb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TrajPb.map_match_point_pb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TrajPb.map_match_point_pb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TrajPb.map_match_point_pb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TrajPb.map_match_point_pb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TrajPb.map_match_point_pb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TrajPb.map_match_point_pb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TrajPb.map_match_point_pb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TrajPb.map_match_point_pb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TrajPb.map_match_point_pb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TrajPb.map_match_point_pb prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code map_match_point_pb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TrajPb.map_match_point_pbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TrajPb.internal_static_map_match_point_pb_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TrajPb.internal_static_map_match_point_pb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TrajPb.map_match_point_pb.class, TrajPb.map_match_point_pb.Builder.class);
      }

      // Construct using com.didichuxing.sts.traj.core.model.TrajPb.map_match_point_pb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        projX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        projY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        linkIdVec_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        linkPassDist_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        srcX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        srcY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        pointSpeed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        pointDirection_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        lineSpeed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000400);
        lineDirection_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000800);
        certainty_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        biztype_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        role_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00004000);
        mapVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        bizstatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        phone_ = 0L;
        bitField0_ = (bitField0_ & ~0x00020000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TrajPb.internal_static_map_match_point_pb_descriptor;
      }

      public TrajPb.map_match_point_pb getDefaultInstanceForType() {
        return TrajPb.map_match_point_pb.getDefaultInstance();
      }

      public TrajPb.map_match_point_pb build() {
        TrajPb.map_match_point_pb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TrajPb.map_match_point_pb buildPartial() {
        TrajPb.map_match_point_pb result = new TrajPb.map_match_point_pb(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.projX_ = projX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.projY_ = projY_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          linkIdVec_ = java.util.Collections.unmodifiableList(linkIdVec_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.linkIdVec_ = linkIdVec_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.linkPassDist_ = linkPassDist_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.srcX_ = srcX_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.srcY_ = srcY_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.pointSpeed_ = pointSpeed_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.pointDirection_ = pointDirection_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.lineSpeed_ = lineSpeed_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.lineDirection_ = lineDirection_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.certainty_ = certainty_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.biztype_ = biztype_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.role_ = role_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.mapVersion_ = mapVersion_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.bizstatus_ = bizstatus_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.phone_ = phone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TrajPb.map_match_point_pb) {
          return mergeFrom((TrajPb.map_match_point_pb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TrajPb.map_match_point_pb other) {
        if (other == TrajPb.map_match_point_pb.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasProjX()) {
          setProjX(other.getProjX());
        }
        if (other.hasProjY()) {
          setProjY(other.getProjY());
        }
        if (!other.linkIdVec_.isEmpty()) {
          if (linkIdVec_.isEmpty()) {
            linkIdVec_ = other.linkIdVec_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLinkIdVecIsMutable();
            linkIdVec_.addAll(other.linkIdVec_);
          }
          onChanged();
        }
        if (other.hasLinkPassDist()) {
          setLinkPassDist(other.getLinkPassDist());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasSrcX()) {
          setSrcX(other.getSrcX());
        }
        if (other.hasSrcY()) {
          setSrcY(other.getSrcY());
        }
        if (other.hasPointSpeed()) {
          setPointSpeed(other.getPointSpeed());
        }
        if (other.hasPointDirection()) {
          setPointDirection(other.getPointDirection());
        }
        if (other.hasLineSpeed()) {
          setLineSpeed(other.getLineSpeed());
        }
        if (other.hasLineDirection()) {
          setLineDirection(other.getLineDirection());
        }
        if (other.hasCertainty()) {
          setCertainty(other.getCertainty());
        }
        if (other.hasBiztype()) {
          setBiztype(other.getBiztype());
        }
        if (other.hasRole()) {
          setRole(other.getRole());
        }
        if (other.hasMapVersion()) {
          setMapVersion(other.getMapVersion());
        }
        if (other.hasBizstatus()) {
          setBizstatus(other.getBizstatus());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {

          return false;
        }
        if (!hasProjX()) {

          return false;
        }
        if (!hasProjY()) {

          return false;
        }
        if (!hasLinkPassDist()) {

          return false;
        }
        if (!hasTimestamp()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TrajPb.map_match_point_pb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TrajPb.map_match_point_pb) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string user_id = 1;
      private Object userId_ = "";
      /**
       * <code>required string user_id = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      // required int32 proj_x = 2;
      private int projX_ ;
      /**
       * <code>required int32 proj_x = 2;</code>
       */
      public boolean hasProjX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 proj_x = 2;</code>
       */
      public int getProjX() {
        return projX_;
      }
      /**
       * <code>required int32 proj_x = 2;</code>
       */
      public Builder setProjX(int value) {
        bitField0_ |= 0x00000002;
        projX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 proj_x = 2;</code>
       */
      public Builder clearProjX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        projX_ = 0;
        onChanged();
        return this;
      }

      // required int32 proj_y = 3;
      private int projY_ ;
      /**
       * <code>required int32 proj_y = 3;</code>
       */
      public boolean hasProjY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 proj_y = 3;</code>
       */
      public int getProjY() {
        return projY_;
      }
      /**
       * <code>required int32 proj_y = 3;</code>
       */
      public Builder setProjY(int value) {
        bitField0_ |= 0x00000004;
        projY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 proj_y = 3;</code>
       */
      public Builder clearProjY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        projY_ = 0;
        onChanged();
        return this;
      }

      // repeated int64 link_id_vec = 4;
      private java.util.List<Long> linkIdVec_ = java.util.Collections.emptyList();
      private void ensureLinkIdVecIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          linkIdVec_ = new java.util.ArrayList<Long>(linkIdVec_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int64 link_id_vec = 4;</code>
       */
      public java.util.List<Long>
          getLinkIdVecList() {
        return java.util.Collections.unmodifiableList(linkIdVec_);
      }
      /**
       * <code>repeated int64 link_id_vec = 4;</code>
       */
      public int getLinkIdVecCount() {
        return linkIdVec_.size();
      }
      /**
       * <code>repeated int64 link_id_vec = 4;</code>
       */
      public long getLinkIdVec(int index) {
        return linkIdVec_.get(index);
      }
      /**
       * <code>repeated int64 link_id_vec = 4;</code>
       */
      public Builder setLinkIdVec(
          int index, long value) {
        ensureLinkIdVecIsMutable();
        linkIdVec_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 link_id_vec = 4;</code>
       */
      public Builder addLinkIdVec(long value) {
        ensureLinkIdVecIsMutable();
        linkIdVec_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 link_id_vec = 4;</code>
       */
      public Builder addAllLinkIdVec(
          Iterable<? extends Long> values) {
        ensureLinkIdVecIsMutable();
        super.addAll(values, linkIdVec_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 link_id_vec = 4;</code>
       */
      public Builder clearLinkIdVec() {
        linkIdVec_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // required int32 link_pass_dist = 5;
      private int linkPassDist_ ;
      /**
       * <code>required int32 link_pass_dist = 5;</code>
       */
      public boolean hasLinkPassDist() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 link_pass_dist = 5;</code>
       */
      public int getLinkPassDist() {
        return linkPassDist_;
      }
      /**
       * <code>required int32 link_pass_dist = 5;</code>
       */
      public Builder setLinkPassDist(int value) {
        bitField0_ |= 0x00000010;
        linkPassDist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 link_pass_dist = 5;</code>
       */
      public Builder clearLinkPassDist() {
        bitField0_ = (bitField0_ & ~0x00000010);
        linkPassDist_ = 0;
        onChanged();
        return this;
      }

      // required int32 timestamp = 6;
      private int timestamp_ ;
      /**
       * <code>required int32 timestamp = 6;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 timestamp = 6;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int32 timestamp = 6;</code>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      // optional int32 src_x = 7;
      private int srcX_ ;
      /**
       * <code>optional int32 src_x = 7;</code>
       */
      public boolean hasSrcX() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 src_x = 7;</code>
       */
      public int getSrcX() {
        return srcX_;
      }
      /**
       * <code>optional int32 src_x = 7;</code>
       */
      public Builder setSrcX(int value) {
        bitField0_ |= 0x00000040;
        srcX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 src_x = 7;</code>
       */
      public Builder clearSrcX() {
        bitField0_ = (bitField0_ & ~0x00000040);
        srcX_ = 0;
        onChanged();
        return this;
      }

      // optional int32 src_y = 8;
      private int srcY_ ;
      /**
       * <code>optional int32 src_y = 8;</code>
       */
      public boolean hasSrcY() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 src_y = 8;</code>
       */
      public int getSrcY() {
        return srcY_;
      }
      /**
       * <code>optional int32 src_y = 8;</code>
       */
      public Builder setSrcY(int value) {
        bitField0_ |= 0x00000080;
        srcY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 src_y = 8;</code>
       */
      public Builder clearSrcY() {
        bitField0_ = (bitField0_ & ~0x00000080);
        srcY_ = 0;
        onChanged();
        return this;
      }

      // optional float point_speed = 9;
      private float pointSpeed_ ;
      /**
       * <code>optional float point_speed = 9;</code>
       */
      public boolean hasPointSpeed() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional float point_speed = 9;</code>
       */
      public float getPointSpeed() {
        return pointSpeed_;
      }
      /**
       * <code>optional float point_speed = 9;</code>
       */
      public Builder setPointSpeed(float value) {
        bitField0_ |= 0x00000100;
        pointSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float point_speed = 9;</code>
       */
      public Builder clearPointSpeed() {
        bitField0_ = (bitField0_ & ~0x00000100);
        pointSpeed_ = 0F;
        onChanged();
        return this;
      }

      // optional float point_direction = 10;
      private float pointDirection_ ;
      /**
       * <code>optional float point_direction = 10;</code>
       */
      public boolean hasPointDirection() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional float point_direction = 10;</code>
       */
      public float getPointDirection() {
        return pointDirection_;
      }
      /**
       * <code>optional float point_direction = 10;</code>
       */
      public Builder setPointDirection(float value) {
        bitField0_ |= 0x00000200;
        pointDirection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float point_direction = 10;</code>
       */
      public Builder clearPointDirection() {
        bitField0_ = (bitField0_ & ~0x00000200);
        pointDirection_ = 0F;
        onChanged();
        return this;
      }

      // optional float line_speed = 11;
      private float lineSpeed_ ;
      /**
       * <code>optional float line_speed = 11;</code>
       */
      public boolean hasLineSpeed() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional float line_speed = 11;</code>
       */
      public float getLineSpeed() {
        return lineSpeed_;
      }
      /**
       * <code>optional float line_speed = 11;</code>
       */
      public Builder setLineSpeed(float value) {
        bitField0_ |= 0x00000400;
        lineSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float line_speed = 11;</code>
       */
      public Builder clearLineSpeed() {
        bitField0_ = (bitField0_ & ~0x00000400);
        lineSpeed_ = 0F;
        onChanged();
        return this;
      }

      // optional float line_direction = 12;
      private float lineDirection_ ;
      /**
       * <code>optional float line_direction = 12;</code>
       */
      public boolean hasLineDirection() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional float line_direction = 12;</code>
       */
      public float getLineDirection() {
        return lineDirection_;
      }
      /**
       * <code>optional float line_direction = 12;</code>
       */
      public Builder setLineDirection(float value) {
        bitField0_ |= 0x00000800;
        lineDirection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float line_direction = 12;</code>
       */
      public Builder clearLineDirection() {
        bitField0_ = (bitField0_ & ~0x00000800);
        lineDirection_ = 0F;
        onChanged();
        return this;
      }

      // optional int32 certainty = 13;
      private int certainty_ ;
      /**
       * <code>optional int32 certainty = 13;</code>
       */
      public boolean hasCertainty() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 certainty = 13;</code>
       */
      public int getCertainty() {
        return certainty_;
      }
      /**
       * <code>optional int32 certainty = 13;</code>
       */
      public Builder setCertainty(int value) {
        bitField0_ |= 0x00001000;
        certainty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 certainty = 13;</code>
       */
      public Builder clearCertainty() {
        bitField0_ = (bitField0_ & ~0x00001000);
        certainty_ = 0;
        onChanged();
        return this;
      }

      // optional int32 biztype = 14;
      private int biztype_ ;
      /**
       * <code>optional int32 biztype = 14;</code>
       */
      public boolean hasBiztype() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 biztype = 14;</code>
       */
      public int getBiztype() {
        return biztype_;
      }
      /**
       * <code>optional int32 biztype = 14;</code>
       */
      public Builder setBiztype(int value) {
        bitField0_ |= 0x00002000;
        biztype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 biztype = 14;</code>
       */
      public Builder clearBiztype() {
        bitField0_ = (bitField0_ & ~0x00002000);
        biztype_ = 0;
        onChanged();
        return this;
      }

      // optional bytes role = 15;
      private com.google.protobuf.ByteString role_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes role = 15;</code>
       */
      public boolean hasRole() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional bytes role = 15;</code>
       */
      public com.google.protobuf.ByteString getRole() {
        return role_;
      }
      /**
       * <code>optional bytes role = 15;</code>
       */
      public Builder setRole(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        role_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes role = 15;</code>
       */
      public Builder clearRole() {
        bitField0_ = (bitField0_ & ~0x00004000);
        role_ = getDefaultInstance().getRole();
        onChanged();
        return this;
      }

      // optional int32 map_version = 16;
      private int mapVersion_ ;
      /**
       * <code>optional int32 map_version = 16;</code>
       */
      public boolean hasMapVersion() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int32 map_version = 16;</code>
       */
      public int getMapVersion() {
        return mapVersion_;
      }
      /**
       * <code>optional int32 map_version = 16;</code>
       */
      public Builder setMapVersion(int value) {
        bitField0_ |= 0x00008000;
        mapVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 map_version = 16;</code>
       */
      public Builder clearMapVersion() {
        bitField0_ = (bitField0_ & ~0x00008000);
        mapVersion_ = 0;
        onChanged();
        return this;
      }

      // optional int32 bizstatus = 17;
      private int bizstatus_ ;
      /**
       * <code>optional int32 bizstatus = 17;</code>
       */
      public boolean hasBizstatus() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional int32 bizstatus = 17;</code>
       */
      public int getBizstatus() {
        return bizstatus_;
      }
      /**
       * <code>optional int32 bizstatus = 17;</code>
       */
      public Builder setBizstatus(int value) {
        bitField0_ |= 0x00010000;
        bizstatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bizstatus = 17;</code>
       */
      public Builder clearBizstatus() {
        bitField0_ = (bitField0_ & ~0x00010000);
        bizstatus_ = 0;
        onChanged();
        return this;
      }

      // optional int64 phone = 18;
      private long phone_ ;
      /**
       * <code>optional int64 phone = 18;</code>
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional int64 phone = 18;</code>
       */
      public long getPhone() {
        return phone_;
      }
      /**
       * <code>optional int64 phone = 18;</code>
       */
      public Builder setPhone(long value) {
        bitField0_ |= 0x00020000;
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 phone = 18;</code>
       */
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00020000);
        phone_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:map_match_point_pb)
    }

    static {
      defaultInstance = new map_match_point_pb(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:map_match_point_pb)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderTraj_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderTraj_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_map_match_point_pb_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_map_match_point_pb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nTraj.proto\"F\n\tOrderTraj\022\020\n\010order_id\030\001 " +
      "\001(\t\022\'\n\npoint_list\030\002 \003(\0132\023.map_match_poin" +
      "t_pb\"\346\002\n\022map_match_point_pb\022\017\n\007user_id\030\001" +
      " \002(\t\022\016\n\006proj_x\030\002 \002(\005\022\016\n\006proj_y\030\003 \002(\005\022\023\n\013" +
      "link_id_vec\030\004 \003(\003\022\026\n\016link_pass_dist\030\005 \002(" +
      "\005\022\021\n\ttimestamp\030\006 \002(\005\022\r\n\005src_x\030\007 \001(\005\022\r\n\005s" +
      "rc_y\030\010 \001(\005\022\023\n\013point_speed\030\t \001(\002\022\027\n\017point" +
      "_direction\030\n \001(\002\022\022\n\nline_speed\030\013 \001(\002\022\026\n\016" +
      "line_direction\030\014 \001(\002\022\021\n\tcertainty\030\r \001(\005\022" +
      "\017\n\007biztype\030\016 \001(\005\022\014\n\004role\030\017 \001(\014\022\023\n\013map_ve",
      "rsion\030\020 \001(\005\022\021\n\tbizstatus\030\021 \001(\005\022\r\n\005phone\030" +
      "\022 \001(\003B-\n#com.didichuxing.sts.traj.core.m" +
      "odelB\006TrajPb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OrderTraj_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OrderTraj_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OrderTraj_descriptor,
              new String[] { "OrderId", "PointList", });
          internal_static_map_match_point_pb_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_map_match_point_pb_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_map_match_point_pb_descriptor,
              new String[] { "UserId", "ProjX", "ProjY", "LinkIdVec", "LinkPassDist", "Timestamp", "SrcX", "SrcY", "PointSpeed", "PointDirection", "LineSpeed", "LineDirection", "Certainty", "Biztype", "Role", "MapVersion", "Bizstatus", "Phone", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
